const UNITS=window.SQL_UNITS,KEY='sql-master-ver3';
const INTRO=[
{title:'データベースって何？',icon:'🗄️',body:`<p>データベースは、大量の情報を整理して保存し、必要なときに素早く取り出せる「情報の保管庫」です。</p><div class="visual"><div class="flow"><div class="flow-box">👩‍💼<strong>利用者</strong><small>患者情報を見たい</small></div><div class="arrow">→</div><div class="db-cylinder">DATABASE</div><div class="arrow">→</div><div class="flow-box">📋<strong>検索結果</strong><small>必要な情報だけ</small></div></div></div><p class="caption">情報を一か所に整理しておくから、検索や集計ができます。</p>`},
{title:'テーブルって何？',icon:'📋',body:`<p>データベースの中では、情報を「テーブル」という表に分けて保存します。Excelの表に近い考え方です。</p><div class="visual"><h3>patients テーブル</h3><table class="mini-table"><thead><tr><th>patient_id</th><th>age</th><th>ward</th></tr></thead><tbody><tr><td>P001</td><td>75</td><td>西6階</td></tr><tr><td>P002</td><td>81</td><td>西7階</td></tr><tr><td>P003</td><td>66</td><td>西6階</td></tr></tbody></table></div><p class="caption">同じ種類の情報を、決まった列でそろえて保存します。</p>`},
{title:'行と列を見分けよう',icon:'↔️',body:`<p><b>列（Column）</b>は情報の項目、<b>行（Row）</b>は1件分のデータです。</p><div class="visual"><table class="mini-table"><thead><tr><th class="highlight-col">patient_id<br><small>列</small></th><th>age</th><th>ward</th></tr></thead><tbody><tr class="highlight-row"><td class="highlight-col">P001</td><td>75</td><td>西6階</td></tr><tr><td class="highlight-col">P002</td><td>81</td><td>西7階</td></tr></tbody></table></div><p class="caption">緑が列、黄色が1行です。</p>`},
{title:'SQLって何？',icon:'💬',body:`<p>SQLは、データベースに質問や依頼を伝えるための言葉です。</p><div class="visual sql-meaning"><div class="meaning-card">🗣️<h3>人の言葉</h3><p>患者一覧を見せて</p></div><div class="arrow">→</div><div class="meaning-card">⌨️<h3>SQL</h3><pre>SELECT *\nFROM patients;</pre></div></div><div class="flow" style="margin-top:16px"><div class="arrow">↓</div></div><div class="flow-box" style="max-width:300px;margin:auto">🗄️ データベースが結果を返す</div>`},
{title:'はじめてのSQLを組み立てよう',icon:'🧩',body:`<p>「patientsテーブルの全列を見せて」というSQLを、単語を順番に押して組み立ててください。</p><div class="visual"><div id="answerLine" class="answer-line"><span class="muted">ここに単語を並べる</span></div><div id="wordBank" class="word-builder"><button class="word" onclick="addWord(this)">FROM</button><button class="word" onclick="addWord(this)">patients</button><button class="word" onclick="addWord(this)">SELECT</button><button class="word" onclick="addWord(this)">*</button></div></div><div id="introFeedback"></div><div class="actions"><button class="btn secondary" onclick="resetWords()">やり直す</button><button class="btn primary" onclick="checkWords()">答え合わせ</button></div>`}
];
let S=JSON.parse(localStorage.getItem(KEY)||'null')||{xp:0,hearts:5,done:{},intro:0,history:[],streak:1};
let current=null,step=0,selected=null,words=[];const app=document.getElementById('app');
function save(){localStorage.setItem(KEY,JSON.stringify(S));refreshTop()}
function refreshTop(){document.getElementById('xp').textContent=S.xp;document.getElementById('hearts').textContent=S.hearts;document.getElementById('streak').textContent=S.streak}
function norm(s){return s.toLowerCase().replace(/;/g,'').replace(/\s+/g,' ').replace(/\s*,\s*/g,',').replace(/\s*\(\s*/g,'(').replace(/\s*\)\s*/g,')').trim()}
function totalSteps(){return S.intro+Object.values(S.done).reduce((a,b)=>a+b,0)}
function goHome(){app.innerHTML=`<section class="hero"><b>初心者から、使えるSQLへ</b><h1>SQLマスターへの道</h1><p>データベースやテーブルの意味からスタート。図解で理解し、選択・穴埋め・結果予測・自力記述の順に身につけます。</p><button class="btn primary" onclick="${S.intro<5?'startIntro()':'showPath()'}">${S.intro<5?'入門から始める':'続きから学ぶ'}</button></section><h2>学習状況</h2><div class="stats-grid"><div class="card"><div class="big">${S.xp}</div><span>獲得XP</span></div><div class="card"><div class="big">${totalSteps()}/55</div><span>修了ステップ</span></div><div class="card"><div class="big">${Object.values(S.done).filter(x=>x>=5).length}/10</div><span>修了ユニット</span></div></div>`}
function startIntro(){step=Math.min(S.intro,4);renderIntro()}
function introShell(content){return `<div class="lesson-head"><div class="lesson-icon">🌱</div><div><small>UNIT 0・STEP ${step+1}/5</small><h1>データベース入門</h1></div></div><div class="steps">${[0,1,2,3,4].map(i=>`<i class="${i<=step?'on':''}"></i>`).join('')}</div><div class="card explain"><div class="lesson-head"><div class="lesson-icon">${INTRO[step].icon}</div><h2>${INTRO[step].title}</h2></div>${content}</div>`}
function renderIntro(){words=[];app.innerHTML=introShell(INTRO[step].body+(step<4?`<div class="actions"><button class="btn secondary" onclick="${step===0?'goHome()':'step--;renderIntro()'}">戻る</button><button class="btn primary" onclick="completeIntro()">理解した</button></div>`:''))}
function completeIntro(){if(S.intro<=step){S.intro=step+1;S.xp+=10;save()}if(step<4){step++;renderIntro()}else{showPath()}}
function addWord(btn){words.push(btn.textContent);btn.disabled=true;document.getElementById('answerLine').innerHTML=words.map(w=>`<span class="word">${w}</span>`).join(' ')}
function resetWords(){words=[];document.querySelectorAll('#wordBank .word').forEach(b=>b.disabled=false);document.getElementById('answerLine').innerHTML='<span class="muted">ここに単語を並べる</span>';document.getElementById('introFeedback').innerHTML=''}
function checkWords(){const ok=words.join(' ')==='SELECT * FROM patients';document.getElementById('introFeedback').innerHTML=`<div class="feedback ${ok?'correct':'wrong'}">${ok?'🎉 正解！ SELECT * FROM patients; です。':'💡 「何を」→「どこから」の順で考えましょう。'}</div>${ok?'<button class="btn primary" onclick="finishIntro()">入門クリア</button>':''}`;if(!ok){S.hearts=Math.max(0,S.hearts-1);save()}}
function finishIntro(){if(S.intro<5){S.intro=5;S.xp+=30;save()}app.innerHTML=introShell(`<div style="text-align:center"><div style="font-size:5rem">🎓</div><h2>データベース入門クリア！</h2><p>データベース、テーブル、行・列、SQLの役割を学びました。</p><button class="btn primary" onclick="showPath()">SELECTの学習へ</button></div>`)}
function progress(id){return S.done[id]||0}function unlocked(id){return S.intro>=5&&(id===1||progress(id-1)>=5)}
function showPath(){app.innerHTML=`<h1>学習ロードマップ</h1><p class="muted">各ユニットは「解説 → 選択 → 穴埋め → 意味を読む → 自力記述」の5ステップです。</p><div class="path"><div class="unit"><button class="node" style="background:#86efac" onclick="startIntro()">🌱</button><div class="unit-card"><small>UNIT 0・${S.intro}/5</small><h3>データベース入門</h3><div class="muted">データベース・テーブル・行と列・SQL</div><div class="progress"><span style="width:${S.intro*20}%"></span></div></div></div>${UNITS.map(u=>`<div class="unit"><button class="node ${unlocked(u.id)?'':'locked'}" style="background:${u.color}" onclick="${unlocked(u.id)?`startUnit(${u.id})`:''}">${unlocked(u.id)?u.icon:'🔒'}</button><div class="unit-card"><small>UNIT ${u.id}・${progress(u.id)}/5</small><h3>${u.title}</h3><div class="muted">${u.goal}</div><div class="progress"><span style="width:${progress(u.id)*20}%"></span></div></div></div>`).join('')}</div>`}
function startUnit(id){current=UNITS.find(u=>u.id===id);step=Math.min(progress(id),4);renderUnit()}
function unitShell(body){return `<div class="lesson-head"><div class="lesson-icon">${current.icon}</div><div><small>UNIT ${current.id}・STEP ${step+1}/5</small><h1>${current.title}</h1></div></div><div class="steps">${[0,1,2,3,4].map(i=>`<i class="${i<=step?'on':''}"></i>`).join('')}</div>${body}`}
function visual(type){if(type==='select')return `<div class="visual visual-select"><table class="mini-table"><tr><th class="all">patient_id</th><th class="all">age</th><th class="all">ward</th></tr><tr><td>P001</td><td>75</td><td>西6階</td></tr></table><div class="caption">SELECT * はすべての列を選びます</div></div>`;if(type==='where')return `<div class="visual visual-where"><table class="mini-table"><tr><th>ID</th><th>age</th></tr><tr class="kept"><td>P001</td><td>78</td></tr><tr class="removed"><td>P002</td><td>64</td></tr><tr class="kept"><td>P003</td><td>82</td></tr></table><div class="caption">WHERE age >= 75 で条件に合う行だけ残ります</div></div>`;if(type==='group')return `<div class="visual"><div class="group-piles"><div class="pile">西6階<br>👤👤<br><b>2人</b></div><div class="pile">西7階<br>👤👤👤<br><b>3人</b></div></div><div class="caption">同じ病棟をまとめて数える</div></div>`;if(type==='join')return `<div class="visual join-wrap"><table class="mini-table"><tr><th class="join-key">ID</th><th>年齢</th></tr><tr><td class="join-key">P001</td><td>75</td></tr></table><div class="arrow">＋</div><table class="mini-table"><tr><th class="join-key">ID</th><th>入院日</th></tr><tr><td class="join-key">P001</td><td>10/1</td></tr></table></div><p class="caption">共通のpatient_idで情報を結びます</p>`;return `<div class="visual"><div class="flow"><div class="flow-box">📋 元データ</div><div class="arrow">→</div><div class="flow-box">⚙️ ${current.title}</div><div class="arrow">→</div><div class="flow-box">✅ 結果</div></div></div>`}
function renderUnit(){selected=null;if(step===0)showLesson();else if(step===1)showChoice('quiz');else if(step===2)showFill();else if(step===3)showChoice('predict');else showPractice()}
function showLesson(){app.innerHTML=unitShell(`<div class="card explain"><h2>まず理解しよう</h2><p>${current.explain}</p>${visual(current.visual)}<h3>基本形</h3><pre class="code">${current.syntax}</pre><h3>例</h3><pre class="code">${current.example}</pre><ul class="points">${current.points.map(x=>`<li>✅ ${x}</li>`).join('')}</ul><div class="actions"><button class="btn secondary" onclick="showPath()">戻る</button><button class="btn primary" onclick="passStep()">理解した</button></div></div>`)}
function showChoice(type){const d=current[type];app.innerHTML=unitShell(`<div class="card"><h2>${type==='quiz'?'正しいものを選ぼう':'このSQLの意味は？'}</h2>${type==='predict'?`<pre class="code">${d.sql}</pre>`:`<p>${d.q}</p>`}<div class="options">${d.options.map((x,i)=>`<button class="option" onclick="selectOption(${i},this)">${i+1}. ${x}</button>`).join('')}</div><div id="feedback"></div><div class="actions"><button class="btn secondary" onclick="step--;renderUnit()">戻る</button><button class="btn primary" onclick="checkChoice('${type}')">答え合わせ</button></div></div>`)}
function showFill(){app.innerHTML=unitShell(`<div class="card"><h2>空欄を埋めよう</h2><p>不足しているSQLを入力してください。</p><div class="fill"><span>${current.fill.before}</span><input id="fillInput" autocomplete="off"><span>${current.fill.after}</span></div><p class="muted">ヒント：${current.fill.hint}</p><div id="feedback"></div><div class="actions"><button class="btn secondary" onclick="step--;renderUnit()">戻る</button><button class="btn primary" onclick="checkFill()">答え合わせ</button></div></div>`)}
function showPractice(){app.innerHTML=unitShell(`<div class="card"><h2>自分でSQLを書こう</h2><p>${current.practice.q}</p><textarea id="sqlInput" class="answer-box" placeholder="ここにSQLを入力してください。最初は空欄です。"></textarea><p class="muted">ヒント：${current.practice.hint}</p><div id="feedback"></div><div class="actions"><button class="btn secondary" onclick="step--;renderUnit()">戻る</button><button class="btn primary" onclick="checkSQL()">判定する</button></div></div>`)}
function selectOption(i,el){selected=i;document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}
function showFeedback(ok,text){document.getElementById('feedback').innerHTML=`<div class="feedback ${ok?'correct':'wrong'}">${ok?'🎉 正解！':'💡 もう一度'}<br>${text}</div>${ok?'<button class="btn primary" onclick="nextStep()">次へ</button>':''}`;if(!ok){S.hearts=Math.max(0,S.hearts-1);save()}}
function checkChoice(type){if(selected===null)return showFeedback(false,'選択肢を選んでください。');const d=current[type],ok=selected===d.answer;showFeedback(ok,d.why);if(ok)markStep()}
function checkFill(){const ok=norm(document.getElementById('fillInput').value)===norm(current.fill.answer);showFeedback(ok,ok?'キーワードを正しく入力できました。':current.fill.hint);if(ok)markStep()}
function checkSQL(){const value=document.getElementById('sqlInput').value;if(!value.trim())return showFeedback(false,'SQLを入力してください。');const ok=[current.practice.answer,...current.practice.alts].map(norm).includes(norm(value));showFeedback(ok,ok?`自力で書けました。解答例：${current.practice.answer}`:'列名・条件・句の順番を確認してください。');if(ok)markStep()}
function markStep(){if(progress(current.id)<=step){S.done[current.id]=step+1;S.xp+=step===4?30:10;S.history.unshift({unit:current.id,title:current.title,step:step+1,at:new Date().toISOString()});save()}}
function passStep(){markStep();nextStep()}
function nextStep(){if(step<4){step++;renderUnit()}else{app.innerHTML=unitShell(`<div class="card" style="text-align:center"><div style="font-size:5rem">🏆</div><h2>UNIT ${current.id} クリア！</h2><p>${current.title}の基本を身につけました。</p><button class="btn primary" onclick="showPath()">学習マップへ</button></div>`)}}
function showStats(){const total=totalSteps();app.innerHTML=`<h1>学習成績</h1><div class="stats-grid"><div class="card"><div class="big">${S.xp}</div><span>総XP</span></div><div class="card"><div class="big">${total}/55</div><span>修了ステップ</span></div><div class="card"><div class="big">${Object.values(S.done).filter(x=>x>=5).length}/10</div><span>修了ユニット</span></div></div><h2>獲得バッジ</h2><div class="card">${total>=1?'<span class="badge">🌱 はじめの一歩</span>':''}${S.intro>=5?'<span class="badge">🎓 DB入門修了</span>':''}${total>=15?'<span class="badge">🔥 継続学習</span>':''}${total>=30?'<span class="badge">⭐ 折り返し</span>':''}${total>=55?'<span class="badge">🏆 SQLマスター</span>':''}${total===0?'<span class="muted">学習を始めるとバッジを獲得できます。</span>':''}</div><button class="btn danger" onclick="if(confirm('進捗をすべて削除しますか？')){localStorage.removeItem(KEY);location.reload()}">進捗をリセット</button>`}
refreshTop();goHome();
